# Generated by Django 2.0.7 on 2019-11-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('upswd', models.CharField(max_length=20)),
            ],
        ),
    ]
